# Consultas SQL


Antes de empezar cargamos nuestro archivo data_berka en nuestro entorno: [enlace](https://sorry.vse.cz/~berka/challenge/pkdd1999/berka.htm)

In [ ]:
!gdown --id 1Osmr7qVN0NMuqYxvLesNn7H4nqPCVbsU

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1Osmr7qVN0NMuqYxvLesNn7H4nqPCVbsU
To: /content/data_berka.db
100% 70.2M/70.2M [00:00<00:00, 201MB/s]

En primer lugar cargamos la extensión que nos va permitir manejar comandos sql directamente en colab

In [ ]:
%load_ext sql

Y conectamos con la base de datos

In [ ]:
%sql sqlite:///data_berka.db

'Connected: @data_berka.db'

Comprobamos esquema

In [ ]:
%%sql
SELECT name,type #SELECT se utiliza para recuperar información de una base de datos. 
FROM sqlite_master
WHERE type = 'table' #WHERE contiene una condición que se debe cumplir.

 * sqlite:///data_berka.db
(sqlite3.OperationalError) near "#SELECT": syntax error
[SQL: SELECT name,type #SELECT se utiliza para recuperar información de una base de datos.
FROM sqlite_master
WHERE type = 'table' #WHERE contiene una condición que se debe cumplir.]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

Una sentencia SELECT debe incluir: una cláusula SELECT, que especifica las columnas que se van a mostrar y una cláusula FROM que especifica la tabla que contiene las columnas enumeradas en la cláusula SELECT.

## Consultas sobre Préstamos

1. Obtener todos los atributos que tiene el banco sobre sus préstamos.

(extra limitar a 20 registros)

In [ ]:
%%sql
SELECT * -- Mediante el uso del asterisco se usa para mostrar todas las columnas de datos de una tabla.
FROM LOAN
LIMIT 20

 * sqlite:///data_berka.db
Done.

[(5314, 1787, 930705, 96396, 12, 8033, 'B'),
 (5316, 1801, 930711, 165960, 36, 4610, 'A'),
 (6863, 9188, 930728, 127080, 60, 2118, 'A'),
 (5325, 1843, 930803, 105804, 36, 2939, 'A'),
 (7240, 11013, 930906, 274740, 60, 4579, 'A'),
 (6687, 8261, 930913, 87840, 24, 3660, 'A'),
 (7284, 11265, 930915, 52788, 12, 4399, 'A'),
 (6111, 5428, 930924, 174744, 24, 7281, 'B'),
 (7235, 10973, 931013, 154416, 48, 3217, 'A'),
 (5997, 4894, 931104, 117024, 24, 4876, 'A'),
 (7121, 10364, 931110, 21924, 36, 609, 'A'),
 (6077, 5270, 931122, 79608, 24, 3317, 'A'),
 (6228, 6034, 931201, 464520, 60, 7742, 'B'),
 (6356, 6701, 931208, 95400, 36, 2650, 'A'),
 (5523, 2705, 931208, 93888, 36, 2608, 'A'),
 (6456, 7123, 931209, 47016, 12, 3918, 'A'),
 (7104, 10320, 931213, 259740, 60, 4329, 'A'),
 (6820, 9034, 931216, 38148, 12, 3179, 'A'),
 (6876, 9236, 931221, 86616, 12, 7218, 'A'),
 (7097, 10266, 931223, 75624, 24, 3151, 'B')]

2. Obtener los campos de fecha (date), cantidad (amount), duración (duration), pagos (payments), estado (status)

(extra limitar a 20 registros)

In [ ]:
%%sql
SELECT date, amount, duration, paymentS, status
FROM LOAN
ORDER BY amount DESC -- ORDER BY se utiliza para ordenar datos, por defecto se ordenan de manera ascendete, por tanto, DESC se utiliza para ordenarlos de manera descendente.
LIMIT 20

 * sqlite:///data_berka.db
Done.

[(971019, 590820, 60, 9847, 'C'),
 (980123, 566640, 60, 9444, 'C'),
 (971112, 541200, 60, 9020, 'D'),
 (950217, 538500, 60, 8975, 'C'),
 (980120, 504000, 60, 8400, 'C'),
 (980522, 495180, 60, 8253, 'C'),
 (941219, 482940, 60, 8049, 'D'),
 (970212, 475680, 48, 9910, 'C'),
 (970907, 473280, 60, 7888, 'D'),
 (971225, 468060, 60, 7801, 'C'),
 (970613, 466608, 48, 9721, 'C'),
 (971227, 465504, 48, 9698, 'D'),
 (950709, 465072, 48, 9689, 'C'),
 (931201, 464520, 60, 7742, 'B'),
 (971105, 460980, 60, 7683, 'D'),
 (960723, 444864, 48, 9268, 'C'),
 (980829, 437460, 60, 7291, 'C'),
 (980213, 428784, 48, 8933, 'C'),
 (961118, 421008, 48, 8771, 'C'),
 (951029, 419880, 60, 6998, 'C')]

3. Obtener los distintos tipos de estado que se presentan en un préstamo.

In [ ]:
%%sql
SELECT DISTINCT status -- SELECT DISTINCT se usa para devolver solo valores distintos (diferentes).
FROM LOAN
ORDER BY status

 * sqlite:///data_berka.db
Done.

[('A',), ('B',), ('C',), ('D',)]

4. Obtener solo los prestamos ya terminados.

In [ ]:
%%sql
SELECT *
FROM LOAN
WHERE status in ("A","B") -- IN se utiliza para probar si un valor está en un juego de valores específico.
LIMIT 100

 * sqlite:///data_berka.db
Done.

[(5314, 1787, 930705, 96396, 12, 8033, 'B'),
 (5316, 1801, 930711, 165960, 36, 4610, 'A'),
 (6863, 9188, 930728, 127080, 60, 2118, 'A'),
 (5325, 1843, 930803, 105804, 36, 2939, 'A'),
 (7240, 11013, 930906, 274740, 60, 4579, 'A'),
 (6687, 8261, 930913, 87840, 24, 3660, 'A'),
 (7284, 11265, 930915, 52788, 12, 4399, 'A'),
 (6111, 5428, 930924, 174744, 24, 7281, 'B'),
 (7235, 10973, 931013, 154416, 48, 3217, 'A'),
 (5997, 4894, 931104, 117024, 24, 4876, 'A'),
 (7121, 10364, 931110, 21924, 36, 609, 'A'),
 (6077, 5270, 931122, 79608, 24, 3317, 'A'),
 (6228, 6034, 931201, 464520, 60, 7742, 'B'),
 (6356, 6701, 931208, 95400, 36, 2650, 'A'),
 (5523, 2705, 931208, 93888, 36, 2608, 'A'),
 (6456, 7123, 931209, 47016, 12, 3918, 'A'),
 (7104, 10320, 931213, 259740, 60, 4329, 'A'),
 (6820, 9034, 931216, 38148, 12, 3179, 'A'),
 (6876, 9236, 931221, 86616, 12, 7218, 'A'),
 (7097, 10266, 931223, 75624, 24, 3151, 'B'),
 (4959, 2, 940105, 80952, 24, 3373, 'A'),
 (6499, 7401, 940105, 80952, 24, 3373, 'A'),
 (5479, 2486, 940110, 24516, 12, 2043, 'A'),
 (6721, 8475, 940121, 21072, 24, 878, 'A'),
 (7259, 11111, 940131, 108144, 36, 3004, 'A'),
 (5285, 1603, 940206, 78936, 12, 6578, 'A'),
 (5189, 1166, 940207, 149040, 48, 3105, 'A'),
 (6650, 8073, 940217, 49320, 12, 4110, 'B'),
 (7226, 10940, 940223, 197748, 36, 5493, 'A'),
 (7262, 11135, 940301, 182628, 36, 5073, 'A'),
 (5519, 2694, 940308, 91632, 12, 7636, 'A'),
 (6577, 7753, 940311, 51696, 24, 2154, 'A'),
 (6509, 7445, 940315, 55368, 24, 2307, 'A'),
 (6520, 7485, 940316, 91200, 24, 3800, 'A'),
 (6699, 8330, 940330, 7656, 24, 319, 'A'),
 (6336, 6555, 940331, 212400, 36, 5900, 'A'),
 (6202, 5891, 940418, 65184, 12, 5432, 'A'),
 (7066, 10131, 940502, 215388, 36, 5983, 'B'),
 (6072, 5256, 940510, 193968, 36, 5388, 'A'),
 (5130, 813, 940511, 24312, 12, 2026, 'A'),
 (6678, 8173, 940520, 80340, 12, 6695, 'A'),
 (6998, 9833, 940521, 97632, 12, 8136, 'A'),
 (6580, 7769, 940522, 196080, 48, 4085, 'A'),
 (6316, 6473, 940526, 76908, 12, 6409, 'B'),
 (6512, 7454, 940526, 63312, 48, 1319, 'A'),
 (6407, 6930, 940526, 25944, 24, 1081, 'A'),
 (5002, 173, 940531, 104808, 12, 8734, 'A'),
 (6647, 8051, 940601, 208320, 48, 4340, 'A'),
 (7137, 10439, 940603, 151560, 24, 6315, 'A'),
 (6903, 9337, 940604, 52128, 24, 2172, 'A'),
 (5918, 4576, 940604, 300204, 36, 8339, 'A'),
 (6642, 8027, 940605, 77640, 12, 6470, 'A'),
 (6210, 5927, 940606, 87216, 48, 1817, 'B'),
 (6279, 6273, 940607, 87360, 24, 3640, 'A'),
 (7249, 11065, 940612, 69360, 48, 1445, 'A'),
 (6112, 5442, 940617, 174744, 24, 7281, 'B'),
 (6596, 7844, 940625, 91584, 24, 3816, 'A'),
 (5657, 3354, 940705, 4980, 12, 415, 'A'),
 (5533, 2762, 940705, 111384, 24, 4641, 'A'),
 (6232, 6051, 940708, 276660, 36, 7685, 'B'),
 (6888, 9265, 940711, 39576, 12, 3298, 'A'),
 (6066, 5228, 940711, 173808, 24, 7242, 'A'),
 (6004, 4937, 940723, 143904, 24, 5996, 'A'),
 (5126, 790, 940724, 208128, 48, 4336, 'B'),
 (7220, 10911, 940728, 131292, 36, 3647, 'A'),
 (6668, 8129, 940730, 74736, 36, 2076, 'A'),
 (5395, 2176, 940730, 299088, 36, 8308, 'B'),
 (6064, 5215, 940804, 14628, 12, 1219, 'A'),
 (6919, 9403, 940805, 120888, 36, 3358, 'A'),
 (6841, 9104, 940807, 172080, 48, 3585, 'A'),
 (6038, 5120, 940810, 323472, 48, 6739, 'A'),
 (6729, 8519, 940811, 74688, 12, 6224, 'A'),
 (7198, 10788, 940823, 45768, 12, 3814, 'A'),
 (6686, 8260, 940825, 224604, 36, 6239, 'A'),
 (5836, 4259, 940827, 79632, 24, 3318, 'A'),
 (7061, 10105, 940827, 121896, 24, 5079, 'A'),
 (5595, 3050, 940902, 82896, 12, 6908, 'A'),
 (5723, 3674, 940910, 23628, 12, 1969, 'A'),
 (6120, 5481, 940911, 209184, 48, 4358, 'A'),
 (6895, 9307, 940919, 41904, 12, 3492, 'A'),
 (5882, 4427, 940926, 87816, 12, 7318, 'A'),
 (5754, 3834, 940928, 23052, 12, 1921, 'A'),
 (6594, 7824, 940928, 189696, 24, 7904, 'B'),
 (6738, 8566, 940929, 230220, 36, 6395, 'B'),
 (6624, 7965, 940930, 71460, 12, 5955, 'A'),
 (6216, 5952, 940930, 141240, 24, 5885, 'A'),
 (6229, 6040, 941002, 11736, 24, 489, 'A'),
 (5887, 4448, 941003, 192744, 36, 5354, 'A'),
 (6808, 8982, 941012, 227880, 36, 6330, 'A'),
 (6297, 6363, 941025, 17508, 12, 1459, 'A'),
 (5161, 1012, 941028, 98184, 24, 4091, 'A'),
 (5390, 2167, 941030, 170256, 24, 7094, 'A'),
 (6150, 5622, 941102, 83016, 12, 6918, 'A'),
 (6223, 5991, 941103, 61056, 48, 1272, 'A'),
 (5032, 290, 941103, 123696, 48, 2577, 'A'),
 (6253, 6148, 941104, 59760, 24, 2490, 'A'),
 (6460, 7133, 941106, 48672, 36, 1352, 'A'),
 (6645, 8041, 941106, 140400, 36, 3900, 'A'),
 (5176, 1106, 941112, 192552, 24, 8023, 'B'),
 (5269, 1527, 941119, 164052, 36, 4557, 'B')]

5. Ordenar lo anterior por duración y cantidad

extra: limitar a 20 elementos

In [ ]:
%%sql
SELECT *
FROM LOAN
WHERE status in ("A","B")
ORDER BY duration, amount DESC
LIMIT 20

 * sqlite:///data_berka.db
Done.

[(6934, 9494, 970209, 116832, 12, 9736, 'A'),
 (5002, 173, 940531, 104808, 12, 8734, 'A'),
 (4986, 97, 970810, 102876, 12, 8573, 'A'),
 (5375, 2106, 961003, 101520, 12, 8460, 'A'),
 (7253, 11079, 970426, 98304, 12, 8192, 'A'),
 (6998, 9833, 940521, 97632, 12, 8136, 'A'),
 (6612, 7907, 970831, 97392, 12, 8116, 'A'),
 (5314, 1787, 930705, 96396, 12, 8033, 'B'),
 (6995, 9814, 960926, 96168, 12, 8014, 'A'),
 (5464, 2419, 950130, 95808, 12, 7984, 'A'),
 (5643, 3273, 970921, 94512, 12, 7876, 'B'),
 (5377, 2116, 970804, 92400, 12, 7700, 'A'),
 (5519, 2694, 940308, 91632, 12, 7636, 'A'),
 (7046, 10049, 970328, 91632, 12, 7636, 'A'),
 (5868, 4361, 970329, 90156, 12, 7513, 'A'),
 (7277, 11231, 971024, 89280, 12, 7440, 'A'),
 (4996, 132, 961106, 88440, 12, 7370, 'A'),
 (5882, 4427, 940926, 87816, 12, 7318, 'A'),
 (7119, 10361, 970602, 86880, 12, 7240, 'A'),
 (6876, 9236, 931221, 86616, 12, 7218, 'A')]

Cargar el resultado de la sql en un DataFrame de Pandas

In [ ]:
#importar librería
import pandas as pd
#ejecutar sql
df = %sql SELECT * FROM LOAN WHERE status in ("A","B") ORDER BY duration, amount DESC
#transformar en DataFrame de pandas y descargarlo en un csv
df.DataFrame().to_csv("first_sql.csv")

 * sqlite:///data_berka.db
Done.

Ex. 1

>Plantear otro filtro para los préstamos (por cantidad, duración, status, etc.)

In [ ]:
%%sql
SELECT *
FROM LOAN
WHERE amount < 500000
ORDER BY amount DESC

 * sqlite:///data_berka.db
Done.

[(6436, 7049, 980522, 495180, 60, 8253, 'C'),
 (7142, 10451, 941219, 482940, 60, 8049, 'D'),
 (6415, 6950, 970212, 475680, 48, 9910, 'C'),
 (6625, 7966, 970907, 473280, 60, 7888, 'D'),
 (5043, 339, 971225, 468060, 60, 7801, 'C'),
 (5486, 2516, 970613, 466608, 48, 9721, 'C'),
 (5976, 4794, 971227, 465504, 48, 9698, 'D'),
 (5970, 4774, 950709, 465072, 48, 9689, 'C'),
 (6228, 6034, 931201, 464520, 60, 7742, 'B'),
 (5731, 3711, 971105, 460980, 60, 7683, 'D'),
 (5725, 3679, 960723, 444864, 48, 9268, 'C'),
 (5561, 2910, 980829, 437460, 60, 7291, 'C'),
 (5491, 2545, 980213, 428784, 48, 8933, 'C'),
 (7101, 10297, 961118, 421008, 48, 8771, 'C'),
 (7304, 11349, 951029, 419880, 60, 6998, 'C'),
 (7154, 10520, 961205, 417600, 60, 6960, 'C'),
 (6704, 8377, 950601, 417060, 60, 6951, 'C'),
 (5419, 2246, 970205, 415800, 60, 6930, 'C'),
 (6237, 6075, 980106, 407952, 48, 8499, 'D'),
 (5830, 4190, 970828, 405780, 60, 6763, 'C'),
 (5938, 4650, 960825, 402000, 60, 6700, 'C'),
 (6055, 5181, 970428, 399120, 60, 6652, 'C'),
 (6272, 6226, 941220, 398640, 60, 6644, 'C'),
 (5329, 1862, 961016, 396120, 60, 6602, 'C'),
 (7271, 11186, 961002, 392460, 60, 6541, 'C'),
 (6338, 6592, 970824, 390660, 60, 6511, 'C'),
 (6554, 7637, 970129, 390096, 48, 8127, 'C'),
 (5589, 3005, 980605, 390000, 48, 8125, 'C'),
 (5236, 1374, 970915, 389136, 48, 8107, 'C'),
 (5282, 1583, 960824, 388512, 48, 8094, 'D'),
 (5318, 1808, 980930, 385584, 48, 8033, 'C'),
 (7209, 10857, 971130, 385560, 60, 6426, 'D'),
 (5174, 1093, 970613, 385104, 48, 8023, 'C'),
 (5563, 2912, 960229, 380160, 60, 6336, 'C'),
 (6926, 9455, 980207, 374760, 60, 6246, 'C'),
 (6585, 7795, 961029, 372120, 60, 6202, 'C'),
 (5041, 319, 970711, 369000, 60, 6150, 'C'),
 (6109, 5422, 960603, 368880, 60, 6148, 'C'),
 (6239, 6083, 970928, 360864, 48, 7518, 'D'),
 (5494, 2572, 960613, 360000, 48, 7500, 'C'),
 (6006, 4948, 961115, 359760, 60, 5996, 'C'),
 (5063, 442, 970710, 357840, 48, 7455, 'D'),
 (4989, 105, 981205, 352704, 48, 7348, 'C'),
 (6118, 5477, 971004, 349392, 48, 7279, 'C'),
 (7100, 10280, 971231, 348120, 60, 5802, 'C'),
 (5418, 2245, 950116, 347952, 48, 7249, 'C'),
 (6938, 9504, 970310, 341280, 60, 5688, 'C'),
 (7195, 10774, 980423, 339168, 48, 7066, 'C'),
 (5532, 2754, 970504, 335280, 48, 6985, 'C'),
 (5991, 4858, 980727, 335184, 48, 6983, 'D'),
 (5772, 3906, 980308, 334620, 60, 5577, 'C'),
 (6705, 8381, 970725, 333648, 48, 6951, 'D'),
 (5042, 330, 980712, 331584, 48, 6908, 'C'),
 (7004, 9869, 950315, 331560, 60, 5526, 'C'),
 (5865, 4354, 981030, 327660, 60, 5461, 'C'),
 (6038, 5120, 940810, 323472, 48, 6739, 'A'),
 (6821, 9037, 980915, 321936, 48, 6707, 'C'),
 (6235, 6062, 980419, 321360, 60, 5356, 'C'),
 (5889, 4456, 980209, 321240, 60, 5354, 'C'),
 (5611, 3115, 961115, 321180, 60, 5353, 'C'),
 (6063, 5213, 960425, 320976, 48, 6687, 'D'),
 (6550, 7614, 960518, 320592, 48, 6679, 'C'),
 (4967, 37, 981014, 318480, 60, 5308, 'D'),
 (6028, 5072, 970209, 317520, 60, 5292, 'C'),
 (7292, 11317, 981122, 317460, 60, 5291, 'C'),
 (5724, 3678, 950205, 316140, 60, 5269, 'D'),
 (5435, 2279, 980601, 314688, 48, 6556, 'C'),
 (7227, 10942, 951002, 314520, 60, 5242, 'C'),
 (7050, 10065, 970923, 311232, 48, 6484, 'C'),
 (6695, 8320, 970604, 309660, 60, 5161, 'C'),
 (6540, 7562, 951231, 309600, 48, 6450, 'C'),
 (5145, 915, 950916, 309552, 48, 6449, 'C'),
 (5758, 3859, 970502, 307200, 60, 5120, 'D'),
 (7085, 10202, 970619, 305424, 48, 6363, 'C'),
 (6087, 5313, 940227, 300660, 60, 5011, 'C'),
 (7001, 9859, 970810, 300600, 60, 5010, 'C'),
 (5918, 4576, 940604, 300204, 36, 8339, 'A'),
 (5395, 2176, 940730, 299088, 36, 8308, 'B'),
 (6350, 6678, 970709, 294384, 48, 6133, 'C'),
 (5363, 2051, 970422, 293880, 60, 4898, 'D'),
 (5469, 2445, 971226, 293160, 60, 4886, 'C'),
 (5354, 2000, 980714, 290820, 60, 4847, 'C'),
 (6175, 5735, 960221, 290700, 60, 4845, 'D'),
 (6007, 4949, 970830, 289920, 48, 6040, 'C'),
 (6435, 7045, 970616, 288720, 48, 6015, 'C'),
 (6526, 7523, 950103, 288468, 36, 8013, 'A'),
 (6736, 8558, 940614, 288360, 60, 4806, 'C'),
 (6153, 5632, 950725, 285600, 60, 4760, 'C'),
 (6877, 9241, 970619, 285240, 60, 4754, 'C'),
 (5148, 940, 960529, 284280, 60, 4738, 'C'),
 (7295, 11328, 980718, 280440, 60, 4674, 'C'),
 (6962, 9646, 980402, 279072, 48, 5814, 'C'),
 (5593, 3037, 960418, 277884, 36, 7719, 'D'),
 (6232, 6051, 940708, 276660, 36, 7685, 'B'),
 (6073, 5263, 961112, 276300, 60, 4605, 'C'),
 (5644, 3293, 981127, 276084, 36, 7669, 'C'),
 (7240, 11013, 930906, 274740, 60, 4579, 'A'),
 (5568, 2933, 940517, 272520, 60, 4542, 'C'),
 (6851, 9138, 970603, 272220, 60, 4537, 'D'),
 (6859, 9167, 980307, 272220, 60, 4537, 'C'),
 (5719, 3664, 970920, 271584, 48, 5658, 'C'),
 (5365, 2055, 980719, 271260, 60, 4521, 'C'),
 (6244, 6118, 950108, 270648, 36, 7518, 'B'),
 (6296, 6358, 960806, 270384, 48, 5633, 'C'),
 (7167, 10644, 980618, 269964, 36, 7499, 'C'),
 (5556, 2872, 970519, 268320, 60, 4472, 'C'),
 (7147, 10478, 980102, 267600, 48, 5575, 'C'),
 (6712, 8405, 951014, 266220, 60, 4437, 'C'),
 (6725, 8489, 950623, 265320, 36, 7370, 'A'),
 (4988, 103, 971206, 265320, 36, 7370, 'D'),
 (5082, 501, 961024, 262980, 60, 4383, 'C'),
 (7122, 10365, 970104, 260640, 36, 7240, 'D'),
 (6655, 8085, 971017, 260400, 60, 4340, 'D'),
 (7176, 10663, 951028, 260028, 36, 7223, 'A'),
 (7104, 10320, 931213, 259740, 60, 4329, 'A'),
 (6012, 4994, 960803, 258444, 36, 7179, 'C'),
 (5614, 3137, 980921, 253560, 60, 4226, 'C'),
 (5606, 3084, 960828, 253512, 36, 7042, 'D'),
 (5170, 1071, 940120, 253200, 60, 4220, 'C'),
 (5169, 1068, 980924, 253200, 60, 4220, 'C'),
 (5060, 426, 940719, 252060, 60, 4201, 'D'),
 (7164, 10613, 980815, 249792, 48, 5204, 'C'),
 (5350, 1967, 960421, 249312, 48, 5194, 'C'),
 (5310, 1762, 950428, 248148, 36, 6893, 'A'),
 (6255, 6158, 970208, 247920, 48, 5165, 'D'),
 (6254, 6157, 971228, 247920, 48, 5165, 'C'),
 (6698, 8327, 960310, 247728, 48, 5161, 'C'),
 (5837, 4260, 940629, 244560, 60, 4076, 'C'),
 (6955, 9627, 951122, 244368, 48, 5091, 'C'),
 (6748, 8645, 981208, 240900, 60, 4015, 'C'),
 (6083, 5305, 980331, 240528, 48, 5011, 'C'),
 (5319, 1811, 940623, 239460, 60, 3991, 'C'),
 (7088, 10233, 970503, 239160, 60, 3986, 'C'),
 (6675, 8158, 971101, 238716, 36, 6631, 'C'),
 (6450, 7099, 980610, 234336, 48, 4882, 'C'),
 (7049, 10063, 970624, 233424, 36, 6484, 'C'),
 (6178, 5742, 951216, 232560, 48, 4845, 'C'),
 (6173, 5724, 970108, 232560, 48, 4845, 'C'),
 (7057, 10093, 951020, 231696, 36, 6436, 'A'),
 (5520, 2699, 980830, 231168, 48, 4816, 'C'),
 (5051, 378, 971011, 230400, 60, 3840, 'C'),
 (6738, 8566, 940929, 230220, 36, 6395, 'B'),
 (5428, 2262, 981202, 230220, 36, 6395, 'C'),
 (6940, 9510, 961122, 228276, 36, 6341, 'C'),
 (6808, 8982, 941012, 227880, 36, 6330, 'A'),
 (6932, 9491, 980625, 225504, 48, 4698, 'C'),
 (6151, 5628, 950425, 225420, 60, 3757, 'C'),
 (6686, 8260, 940825, 224604, 36, 6239, 'A'),
 (5625, 3189, 961215, 222180, 60, 3703, 'D'),
 (6142, 5591, 970121, 221880, 60, 3698, 'C'),
 (5876, 4413, 950208, 221280, 48, 4610, 'C'),
 (6715, 8411, 960506, 220620, 60, 3677, 'C'),
 (6568, 7713, 980225, 220440, 60, 3674, 'C'),
 (6660, 8094, 970509, 220428, 36, 6123, 'C'),
 (5973, 4784, 971124, 219456, 48, 4572, 'C'),
 (7037, 10022, 980103, 218064, 48, 4543, 'C'),
 (7243, 11042, 951204, 217152, 36, 6032, 'A'),
 (5128, 808, 960411, 215616, 48, 4492, 'D'),
 (7066, 10131, 940502, 215388, 36, 5983, 'B'),
 (6861, 9179, 980228, 215040, 60, 3584, 'C'),
 (5369, 2080, 970912, 214596, 36, 5961, 'C'),
 (5989, 4852, 960304, 213300, 36, 5925, 'C'),
 (7255, 11096, 970609, 213300, 60, 3555, 'C'),
 (5823, 4144, 980621, 212976, 36, 5916, 'C'),
 (6336, 6555, 940331, 212400, 36, 5900, 'A'),
 (7035, 10005, 980729, 210744, 36, 5854, 'C'),
 (5086, 525, 970716, 210384, 48, 4383, 'C'),
 (6120, 5481, 940911, 209184, 48, 4358, 'A'),
 (5334, 1876, 980910, 209040, 24, 8710, 'C'),
 (7168, 10645, 980705, 208332, 36, 5787, 'C'),
 (6647, 8051, 940601, 208320, 48, 4340, 'A'),
 (5126, 790, 940724, 208128, 48, 4336, 'B'),
 (5674, 3418, 970610, 207264, 48, 4318, 'C'),
 (5351, 1978, 941204, 205200, 36, 5700, 'A'),
 (5963, 4746, 970907, 204780, 60, 3413, 'C'),
 (5160, 1011, 951218, 204000, 60, 3400, 'C'),
 (6468, 7176, 971130, 203940, 60, 3399, 'C'),
 (6097, 5362, 970821, 202848, 48, 4226, 'C'),
 (5312, 1772, 960313, 202788, 36, 5633, 'C'),
 (5470, 2456, 960415, 200976, 48, 4187, 'C'),
 (5450, 2345, 941211, 199680, 60, 3328, 'C'),
 (7166, 10630, 950624, 198240, 24, 8260, 'A'),
 (7181, 10679, 971002, 197808, 24, 8242, 'C'),
 (7226, 10940, 940223, 197748, 36, 5493, 'A'),
 (5072, 472, 970428, 196800, 24, 8200, 'D'),
 (7171, 10650, 980224, 196224, 48, 4088, 'C'),
 (6580, 7769, 940522, 196080, 48, 4085, 'A'),
 (7036, 10019, 960925, 194940, 36, 5415, 'C'),
 (6403, 6924, 951205, 194880, 48, 4060, 'C'),
 (7129, 10404, 980301, 194280, 60, 3238, 'C'),
 (5281, 1580, 971127, 194256, 24, 8094, 'C'),
 (6442, 7082, 980208, 194160, 48, 4045, 'C'),
 (6072, 5256, 940510, 193968, 36, 5388, 'A'),
 (5887, 4448, 941003, 192744, 36, 5354, 'A'),
 (5886, 4447, 961031, 192744, 36, 5354, 'C'),
 (5176, 1106, 941112, 192552, 24, 8023, 'B'),
 (6545, 7606, 951212, 191880, 60, 3198, 'C'),
 (6872, 9227, 980429, 191580, 60, 3193, 'C'),
 (5270, 1528, 970721, 191088, 48, 3981, 'C'),
 (5293, 1656, 981029, 189792, 48, 3954, 'C'),
 (6594, 7824, 940928, 189696, 24, 7904, 'B'),
 (6589, 7815, 960101, 189696, 24, 7904, 'A'),
 (6836, 9093, 940803, 189300, 60, 3155, 'C'),
 (5151, 960, 950524, 189060, 60, 3151, 'C'),
 (6933, 9493, 950909, 188688, 48, 3931, 'C'),
 (6908, 9353, 970608, 188616, 24, 7859, 'C'),
 (5158, 1004, 980411, 188532, 36, 5237, 'C'),
 (5045, 347, 950501, 187224, 24, 7801, 'B'),
 (5136, 846, 960728, 187104, 24, 7796, 'A'),
 (6810, 9006, 960608, 186384, 48, 3883, 'C'),
 (6793, 8931, 970130, 186300, 60, 3105, 'C'),
 (5414, 2228, 950329, 185952, 48, 3874, 'C'),
 (6746, 8639, 980606, 185640, 60, 3094, 'C'),
 (5226, 1318, 981011, 185544, 36, 5154, 'C'),
 (6207, 5912, 980623, 184620, 60, 3077, 'C'),
 (5209, 1250, 961125, 182640, 48, 3805, 'C'),
 (7262, 11135, 940301, 182628, 36, 5073, 'A'),
 (5409, 2218, 951118, 182040, 60, 3034, 'C'),
 (6302, 6397, 960916, 181020, 60, 3017, 'C'),
 (6011, 4981, 961128, 179328, 48, 3736, 'C'),
 (5140, 873, 980224, 178500, 60, 2975, 'C'),
 (6196, 5837, 970914, 177804, 36, 4939, 'C'),
 (5624, 3166, 950103, 177744, 48, 3703, 'D'),
 (6147, 5602, 971228, 177504, 48, 3698, 'C'),
 (5360, 2035, 980125, 176328, 36, 4898, 'C'),
 (6961, 9645, 960606, 176148, 36, 4893, 'C'),
 (5699, 3562, 980524, 174960, 24, 7290, 'C'),
 (5698, 3556, 980922, 174840, 60, 2914, 'C'),
 (6111, 5428, 930924, 174744, 24, 7281, 'B'),
 (6112, 5442, 940617, 174744, 24, 7281, 'B'),
 (6732, 8533, 960919, 174048, 48, 3626, 'C'),
 (6066, 5228, 940711, 173808, 24, 7242, 'A'),
 (6734, 8547, 960530, 173016, 36, 4806, 'C'),
 (5304, 1718, 980820, 172272, 24, 7178, 'C'),
 (6841, 9104, 940807, 172080, 48, 3585, 'A'),
 (6078, 5283, 980909, 170832, 48, 3559, 'C'),
 (6755, 8713, 980724, 170700, 60, 2845, 'C'),
 (6552, 7632, 980108, 170448, 48, 3551, 'C'),
 (5390, 2167, 941030, 170256, 24, 7094, 'A'),
 (7241, 11021, 950304, 168984, 24, 7041, 'B'),
 (5956, 4725, 971104, 168264, 36, 4674, 'C'),
 (7055, 10079, 940406, 167100, 60, 2785, 'C'),
 (5316, 1801, 930711, 165960, 36, 4610, 'A'),
 (4973, 67, 960502, 165960, 24, 6915, 'A'),
 (5265, 1498, 981007, 165780, 60, 2763, 'C'),
 (6014, 4999, 970518, 165168, 36, 4588, 'C'),
 (5482, 2496, 960112, 165120, 60, 2752, 'C'),
 (6871, 9225, 970413, 164256, 48, 3422, 'C'),
 (5850, 4293, 970522, 164196, 36, 4561, 'C'),
 (5269, 1527, 941119, 164052, 36, 4557, 'B'),
 (6856, 9156, 981201, 163332, 36, 4537, 'C'),
 (5942, 4681, 970315, 162624, 48, 3388, 'C'),
 (4990, 110, 970908, 162576, 36, 4516, 'C'),
 (5337, 1886, 960731, 162468, 36, 4513, 'C'),
 (5706, 3608, 960524, 161496, 36, 4486, 'C'),
 (5027, 276, 981202, 160920, 36, 4470, 'C'),
 (6633, 7997, 980205, 160656, 24, 6694, 'C'),
 (5451, 2350, 970511, 159744, 48, 3328, 'C'),
 (5804, 4079, 950405, 158976, 48, 3312, 'C'),
 (5713, 3629, 950530, 158760, 60, 2646, 'C'),
 (6104, 5395, 970905, 158184, 36, 4394, 'C'),
 (6948, 9560, 980315, 157068, 36, 4363, 'C'),
 (5453, 2361, 950401, 156672, 36, 4352, 'A'),
 (5527, 2728, 980615, 156420, 60, 2607, 'C'),
 (5124, 785, 980212, 156096, 36, 4336, 'C'),
 (6667, 8127, 960715, 155880, 24, 6495, 'A'),
 (7279, 11244, 971211, 155760, 24, 6490, 'C'),
 (6471, 7184, 960804, 155640, 24, 6485, 'A'),
 (5591, 3021, 961204, 155616, 48, 3242, 'C'),
 (6818, 9030, 961212, 155616, 48, 3242, 'C'),
 (7189, 10728, 960321, 154656, 48, 3222, 'C'),
 (7235, 10973, 931013, 154416, 48, 3217, 'A'),
 (5765, 3875, 980210, 153936, 24, 6414, 'C'),
 (6541, 7565, 970817, 153504, 48, 3198, 'C'),
 (6607, 7894, 971021, 153144, 36, 4254, 'C'),
 (7221, 10915, 980611, 152460, 60, 2541, 'C'),
 (6486, 7240, 980115, 152160, 60, 2536, 'C'),
 (6986, 9750, 950211, 151728, 48, 3161, 'D'),
 (7137, 10439, 940603, 151560, 24, 6315, 'A'),
 (5815, 4116, 980603, 151200, 36, 4200, 'C'),
 (6313, 6461, 970615, 150912, 36, 4192, 'C'),
 (6010, 4969, 970306, 150180, 60, 2503, 'C'),
 (6103, 5385, 940407, 149340, 60, 2489, 'C'),
 (5189, 1166, 940207, 149040, 48, 3105, 'A'),
 (7246, 11054, 960820, 148920, 60, 2482, 'C'),
 (5210, 1252, 970401, 148140, 36, 4115, 'C'),
 (5656, 3353, 970209, 146064, 24, 6086, 'C'),
 (6632, 7990, 980423, 144960, 48, 3020, 'C'),
 (6004, 4937, 940723, 143904, 24, 5996, 'A'),
 (5320, 1819, 980111, 143676, 36, 3991, 'C'),
 (5301, 1698, 960706, 141948, 36, 3943, 'C'),
 (5988, 4851, 960822, 141648, 24, 5902, 'A'),
 (6216, 5952, 940930, 141240, 24, 5885, 'A'),
 (6136, 5572, 980419, 140880, 60, 2348, 'C'),
 (7202, 10812, 980529, 140688, 48, 2931, 'C'),
 (5683, 3460, 980529, 140688, 48, 2931, 'C'),
 (6645, 8041, 941106, 140400, 36, 3900, 'A'),
 (6571, 7733, 980512, 140064, 24, 5836, 'C'),
 (6965, 9656, 950613, 139536, 24, 5814, 'A'),
 (6402, 6922, 981206, 139488, 24, 5812, 'C'),
 (5415, 2236, 960926, 139464, 36, 3874, 'D'),
 (5805, 4081, 951128, 137904, 24, 5746, 'B'),
 (6358, 6715, 950114, 137880, 60, 2298, 'D'),
 (7067, 10134, 980111, 136368, 24, 5682, 'C'),
 (5501, 2622, 980521, 136344, 24, 5681, 'C'),
 (5900, 4503, 960101, 135360, 48, 2820, 'C'),
 (6694, 8316, 950319, 134784, 24, 5616, 'A'),
 (6992, 9790, 960727, 133968, 48, 2791, 'C'),
 (5773, 3907, 980316, 133848, 24, 5577, 'C'),
 (7151, 10493, 980218, 133800, 24, 5575, 'C'),
 (7220, 10911, 940728, 131292, 36, 3647, 'A'),
 (5616, 3143, 980515, 130896, 24, 5454, 'C'),
 (6544, 7594, 971211, 130464, 48, 2718, 'C'),
 (7308, 11362, 961227, 129408, 24, 5392, 'A'),
 (6075, 5267, 971126, 129312, 24, 5388, 'D'),
 (6013, 4995, 960203, 128988, 36, 3583, 'D'),
 (5206, 1242, 970907, 128544, 24, 5356, 'C'),
 (6641, 8026, 970909, 128268, 36, 3563, 'C'),
 (6355, 6699, 970924, 127200, 48, 2650, 'C'),
 (6863, 9188, 930728, 127080, 60, 2118, 'A'),
 (6996, 9828, 950413, 126600, 24, 5275, 'A'),
 (5245, 1407, 980117, 125472, 24, 5228, 'C'),
 (5241, 1389, 980902, 125472, 24, 5228, 'C'),
 (6785, 8899, 951225, 125340, 60, 2089, 'C'),
 (6386, 6856, 970430, 124344, 36, 3454, 'C'),
 (5032, 290, 941103, 123696, 48, 2577, 'A'),
 (6190, 5794, 960506, 123600, 60, 2060, 'C'),
 (7130, 10411, 961211, 123408, 24, 5142, 'A'),
 (5260, 1480, 980119, 123300, 36, 3425, 'C'),
 (5610, 3112, 960224, 123216, 48, 2567, 'C'),
 (6866, 9201, 980205, 122472, 24, 5103, 'C'),
 (7061, 10105, 940827, 121896, 24, 5079, 'A'),
 (6919, 9403, 940805, 120888, 36, 3358, 'A'),
 (7250, 11069, 970304, 119136, 48, 2482, 'C'),
 (6076, 5269, 970202, 117420, 60, 1957, 'C'),
 (5997, 4894, 931104, 117024, 24, 4876, 'A'),
 (6934, 9494, 970209, 116832, 12, 9736, 'A'),
 (6353, 6686, 971225, 116496, 24, 4854, 'C'),
 (6984, 9730, 970815, 116040, 60, 1934, 'C'),
 (7192, 10738, 941221, 115992, 36, 3222, 'A'),
 (7233, 10963, 961225, 115812, 36, 3217, 'C'),
 (6985, 9731, 951122, 113796, 36, 3161, 'A'),
 (7213, 10884, 960213, 113544, 36, 3154, 'C'),
 (7091, 10243, 980922, 113436, 36, 3151, 'C'),
 (5034, 303, 980530, 112752, 36, 3132, 'C'),
 (5533, 2762, 940705, 111384, 24, 4641, 'A'),
 (6508, 7437, 980419, 110736, 48, 2307, 'C'),
 (4968, 38, 980419, 110736, 48, 2307, 'C'),
 (6309, 6434, 961111, 110136, 24, 4589, 'A'),
 (6015, 5001, 961109, 110112, 24, 4588, 'A'),
 (5015, 226, 980712, 109344, 12, 9112, 'C'),
 (5154, 993, 980701, 108720, 60, 1812, 'C'),
 (7259, 11111, 940131, 108144, 36, 3004, 'A'),
 (5959, 4727, 950811, 107640, 24, 4485, 'A'),
 (5779, 3942, 971014, 107352, 36, 2982, 'C'),
 (5940, 4660, 970528, 106944, 24, 4456, 'C'),
 (5799, 4052, 971228, 106128, 36, 2948, 'C'),
 (5325, 1843, 930803, 105804, 36, 2939, 'A'),
 (6320, 6495, 980428, 104964, 12, 8747, 'C'),
 (5002, 173, 940531, 104808, 12, 8734, 'A'),
 (6950, 9591, 950411, 104712, 24, 4363, 'A'),
 (6949, 9583, 951212, 104712, 24, 4363, 'A'),
 (6169, 5700, 950316, 103680, 60, 1728, 'D'),
 (4986, 97, 970810, 102876, 12, 8573, 'A'),
 (5110, 675, 970401, 102240, 60, 1704, 'C'),
 (5375, 2106, 961003, 101520, 12, 8460, 'A'),
 (5044, 344, 941221, 100980, 60, 1683, 'C'),
 (5817, 4127, 970815, 100800, 24, 4200, 'D'),
 (6346, 6649, 970522, 100260, 60, 1671, 'C'),
 (6816, 9017, 960326, 100224, 48, 2088, 'D'),
 (5862, 4342, 971209, 100128, 24, 4172, 'C'),
 (5253, 1447, 970603, 100080, 48, 2085, 'C'),
 (6913, 9377, 970429, 99936, 24, 4164, 'C'),
 (6469, 7180, 981117, 99744, 24, 4156, 'C'),
 (5208, 1247, 950316, 99696, 48, 2077, 'D'),
 (5449, 2343, 951104, 99336, 24, 4139, 'A'),
 (6665, 8114, 970815, 99300, 60, 1655, 'C'),
 (6168, 5698, 981121, 99216, 36, 2756, 'C'),
 (5999, 4907, 960103, 98832, 48, 2059, 'C'),
 (6157, 5650, 950710, 98592, 24, 4108, 'A'),
 (7253, 11079, 970426, 98304, 12, 8192, 'A'),
 (5161, 1012, 941028, 98184, 24, 4091, 'A'),
 (6677, 8169, 970812, 97980, 60, 1633, 'C'),
 (6998, 9833, 940521, 97632, 12, 8136, 'A'),
 (6612, 7907, 970831, 97392, 12, 8116, 'A'),
 (5877, 4414, 950223, 97224, 24, 4051, 'A'),
 (5953, 4715, 970314, 97176, 24, 4049, 'C'),
 (5774, 3916, 980712, 96984, 36, 2694, 'C'),
 (6421, 6985, 960725, 96768, 36, 2688, 'C'),
 (5314, 1787, 930705, 96396, 12, 8033, 'B'),
 (6995, 9814, 960926, 96168, 12, 8014, 'A'),
 (5464, 2419, 950130, 95808, 12, 7984, 'A'),
 (6356, 6701, 931208, 95400, 36, 2650, 'A'),
 (5643, 3273, 970921, 94512, 12, 7876, 'B'),
 (6562, 7674, 970321, 94488, 24, 3937, 'C'),
 (5895, 4473, 970103, 93960, 60, 1566, 'C'),
 (5523, 2705, 931208, 93888, 36, 2608, 'A'),
 (5525, 2720, 980427, 93888, 36, 2608, 'C'),
 (6644, 8039, 961020, 93600, 24, 3900, 'A'),
 (6730, 8523, 980215, 93036, 12, 7753, 'C'),
 (5413, 2227, 951212, 92976, 24, 3874, 'A'),
 (5377, 2116, 970804, 92400, 12, 7700, 'A'),
 (5519, 2694, 940308, 91632, 12, 7636, 'A'),
 (7046, 10049, 970328, 91632, 12, 7636, 'A'),
 (6596, 7844, 940625, 91584, 24, 3816, 'A'),
 (5036, 309, 981125, 91248, 48, 1901, 'C'),
 (6520, 7485, 940316, 91200, 24, 3800, 'A'),
 (5088, 544, 960822, 91152, 24, 3798, 'A'),
 (6088, 5317, 970307, 90180, 36, 2505, 'C'),
 (5868, 4361, 970329, 90156, 12, 7513, 'A'),
 (7263, 11138, 960119, 89880, 24, 3745, 'A'),
 (5495, 2580, 960802, 89340, 60, 1489, 'C'),
 (7013, 9928, 960802, 89340, 60, 1489, 'C'),
 (7277, 11231, 971024, 89280, 12, 7440, 'A'),
 (6696, 8321, 940509, 89040, 60, 1484, 'C'),
 (7115, 10351, 970304, 88704, 48, 1848, 'C'),
 (5585, 2988, 980708, 88608, 12, 7384, 'C'),
 (4996, 132, 961106, 88440, 12, 7370, 'A'),
 (6763, 8772, 970619, 88272, 48, 1839, 'C'),
 (6969, 9673, 980912, 88200, 36, 2450, 'C'),
 (6687, 8261, 930913, 87840, 24, 3660, 'A'),
 (5882, 4427, 940926, 87816, 12, 7318, 'A'),
 (5933, 4631, 971213, 87528, 24, 3647, 'C'),
 (6279, 6273, 940607, 87360, 24, 3640, 'A'),
 (6278, 6265, 970610, 87360, 24, 3640, 'C'),
 (6210, 5927, 940606, 87216, 48, 1817, 'B'),
 (5138, 854, 950530, 87216, 48, 1817, 'C'),
 (7119, 10361, 970602, 86880, 12, 7240, 'A'),
 (6876, 9236, 931221, 86616, 12, 7218, 'A'),
 (6921, 9422, 961029, 86184, 12, 7182, 'A'),
 (5366, 2062, 961029, 86184, 12, 7182, 'A'),
 (5893, 4467, 980803, 86184, 36, 2394, 'C'),
 (6726, 8492, 950903, 85860, 60, 1431, 'C'),
 (6751, 8680, 960714, 85716, 36, 2381, 'C'),
 (6283, 6289, 960811, 85632, 48, 1784, 'C'),

Operadores de comparación en WHERE: 

*   = igual que 
*   < menor que, > mayor que
*   <> o ! no es igual que

 Ex. 2 

> Seleccionar fecha, cantidad, duración y pagos de aquellos préstamos que han sido terminados con una duración mayor de 12 meses ordenados de mayor a menor cantidad de dinero

>extra: volcar en un DataFrame

In [ ]:
%%sql
SELECT date, amount, duration, payments
FROM LOAN
WHERE status in ("A","B") AND duration > 12 -- Con AND los resultados serán las filas que cumplan ambas condiciones especificas en WHERE.
ORDER BY amount DESC
LIMIT 100

 * sqlite:///data_berka.db
Done.

[(931201, 464520, 60, 7742),
 (940810, 323472, 48, 6739),
 (940604, 300204, 36, 8339),
 (940730, 299088, 36, 8308),
 (950103, 288468, 36, 8013),
 (940708, 276660, 36, 7685),
 (930906, 274740, 60, 4579),
 (950108, 270648, 36, 7518),
 (950623, 265320, 36, 7370),
 (951028, 260028, 36, 7223),
 (931213, 259740, 60, 4329),
 (950428, 248148, 36, 6893),
 (951020, 231696, 36, 6436),
 (940929, 230220, 36, 6395),
 (941012, 227880, 36, 6330),
 (940825, 224604, 36, 6239),
 (951204, 217152, 36, 6032),
 (940502, 215388, 36, 5983),
 (940331, 212400, 36, 5900),
 (940911, 209184, 48, 4358),
 (940601, 208320, 48, 4340),
 (940724, 208128, 48, 4336),
 (941204, 205200, 36, 5700),
 (950624, 198240, 24, 8260),
 (940223, 197748, 36, 5493),
 (940522, 196080, 48, 4085),
 (940510, 193968, 36, 5388),
 (941003, 192744, 36, 5354),
 (941112, 192552, 24, 8023),
 (940928, 189696, 24, 7904),
 (960101, 189696, 24, 7904),
 (950501, 187224, 24, 7801),
 (960728, 187104, 24, 7796),
 (940301, 182628, 36, 5073),
 (930924, 174744, 24, 7281),
 (940617, 174744, 24, 7281),
 (940711, 173808, 24, 7242),
 (940807, 172080, 48, 3585),
 (941030, 170256, 24, 7094),
 (950304, 168984, 24, 7041),
 (930711, 165960, 36, 4610),
 (960502, 165960, 24, 6915),
 (941119, 164052, 36, 4557),
 (950401, 156672, 36, 4352),
 (960715, 155880, 24, 6495),
 (960804, 155640, 24, 6485),
 (931013, 154416, 48, 3217),
 (940603, 151560, 24, 6315),
 (940207, 149040, 48, 3105),
 (940723, 143904, 24, 5996),
 (960822, 141648, 24, 5902),
 (940930, 141240, 24, 5885),
 (941106, 140400, 36, 3900),
 (950613, 139536, 24, 5814),
 (951128, 137904, 24, 5746),
 (950319, 134784, 24, 5616),
 (940728, 131292, 36, 3647),
 (961227, 129408, 24, 5392),
 (930728, 127080, 60, 2118),
 (950413, 126600, 24, 5275),
 (941103, 123696, 48, 2577),
 (961211, 123408, 24, 5142),
 (940827, 121896, 24, 5079),
 (940805, 120888, 36, 3358),
 (931104, 117024, 24, 4876),
 (941221, 115992, 36, 3222),
 (951122, 113796, 36, 3161),
 (940705, 111384, 24, 4641),
 (961111, 110136, 24, 4589),
 (961109, 110112, 24, 4588),
 (940131, 108144, 36, 3004),
 (950811, 107640, 24, 4485),
 (930803, 105804, 36, 2939),
 (950411, 104712, 24, 4363),
 (951212, 104712, 24, 4363),
 (951104, 99336, 24, 4139),
 (950710, 98592, 24, 4108),
 (941028, 98184, 24, 4091),
 (950223, 97224, 24, 4051),
 (931208, 95400, 36, 2650),
 (931208, 93888, 36, 2608),
 (961020, 93600, 24, 3900),
 (951212, 92976, 24, 3874),
 (940625, 91584, 24, 3816),
 (940316, 91200, 24, 3800),
 (960822, 91152, 24, 3798),
 (960119, 89880, 24, 3745),
 (930913, 87840, 24, 3660),
 (940607, 87360, 24, 3640),
 (940606, 87216, 48, 1817),
 (960922, 84120, 24, 3505),
 (940105, 80952, 24, 3373),
 (940105, 80952, 24, 3373),
 (940827, 79632, 24, 3318),
 (931122, 79608, 24, 3317),
 (950311, 76680, 24, 3195),
 (950111, 76416, 24, 3184),
 (931223, 75624, 24, 3151),
 (940730, 74736, 36, 2076),
 (951031, 73836, 36, 2051)]

¿Cuantos registros cumplen esta condición?

In [ ]:
%%sql
SELECT count(*) -- Count (*) devuelve el número de filas de una tabla.
FROM LOAN
WHERE status in ("A","B") AND duration > 12

 * sqlite:///data_berka.db
Done.

[(131,)]

COUNT: devuelve el número de valores no nulos de la columna de expresión. 

COUNT(*): querermos asegurarnos de contar todas las filas (duplicados incluidos).

¿Cuantos préstamos hay en ejecución (running) con duración entre 24 y 48 meses?

In [ ]:
%%sql
SELECT count(*)
FROM LOAN
WHERE status in ("C","D") AND duration between 24 and 48 -- Between...And en WHERE devuelve un rango de valores entre los límites inferior y superior, incluyendo estos.

 * sqlite:///data_berka.db
Done.

[(279,)]

BETWEEN...AND: se utiliza para seleccionar y mostrar las filas según un rango de valores.

## Group By

7. ¿Cuántos préstamos hay por cada estado y cual es la media de la cantidad de dinero prestado?
Where: se filtran los registros antes de agruparlos; Having: se filtran los grupos tras obtenerlos.

In [ ]:
%%sql
SELECT status, count(*) as total, avg(amount) -- AVG = Media
FROM LOAN 
WHERE duration >= 24
GROUP BY status -- Se utiliza GROUP BY para dividir las filas de una tabla en grupos más pequeños.
HAVING total > 25 -- Se utiliza HAVING para restringir los grupos devueltos por una cláusula GROUP BY.
ORDER BY total DESC

 * sqlite:///data_berka.db
Done.

[('C', 376, 180343.1489361702),
 ('A', 110, 122425.2),
 ('D', 44, 254127.27272727274)]

WHERE para restringir las filas; y HAVING para restringir los grupos devueltos por una cláusula GROUP BY.

8. Por cada Región, quiero contar el número de ciudades y obtener el total del número de habitantes de la región

In [ ]:
%%sql
SELECT A3, count(A2) no_district, sum(A9), sum(A4) total_hab -- SUM se utiliza con las columnas que almacenan los datos numéricos para buscar la suma o total de valores.
FROM DISTRICT
WHERE NOT A3 = "Prague" -- Donde No sea Praga.
GROUP BY A3

 * sqlite:///data_berka.db
Done.

[('central Bohemia', 12, 66, 1105234),
 ('east Bohemia', 11, 86, 1234781),
 ('north Bohemia', 10, 70, 1178977),
 ('north Moravia', 11, 60, 1970302),
 ('south Bohemia', 8, 48, 700595),
 ('south Moravia', 14, 82, 2054989),
 ('west Bohemia', 10, 69, 859306)]

9. Contar ordenes permanentes (domiciliaciones) por banco y tipo de transacción

In [ ]:
%%sql
SELECT bank_to, k_symbol, count(*) as c
FROM PERMANENT_ORDER
WHERE amount < 500
GROUP BY bank_to, k_symbol
ORDER BY bank_to

# JOIN

10. ¿Cuántas cuentas de frecuencia mensual tienen un un préstamo activo?

In [ ]:
%%sql
SELECT loan_id, A4, A9, A10, A11, c.birth_number, l.date loan_date, amount, duration, payments, frequency, a.date acc_date, status
FROM LOAN l, ACCOUNT a, DISTRICT d, DISPOSITION dp, CLIENT c
WHERE l.account_id = a.account_id -- Condición de unión join loan / account
AND a. district_id = d.A1 -- Condición de unión join loan / district
AND dp.account_id = a.account_id -- join account / disposition
AND status in ("A", "B")
ORDER BY amount DESC, a.date DESC
LIMIT 10

 * sqlite:///data_berka.db
Done.

[(6228, 77963, 4, 51.5, 8546, '706213', 931201, 464520, 60, 7742, 'weekly', 930319, 'B'),
 (6228, 77963, 4, 51.5, 8546, '450204', 931201, 464520, 60, 7742, 'weekly', 930319, 'B'),
 (6228, 77963, 4, 51.5, 8546, '406009', 931201, 464520, 60, 7742, 'weekly', 930319, 'B'),
 (6228, 77963, 4, 51.5, 8546, '561201', 931201, 464520, 60, 7742, 'weekly', 930319, 'B'),
 (6228, 77963, 4, 51.5, 8546, '605703', 931201, 464520, 60, 7742, 'weekly', 930319, 'B'),
 (6228, 77963, 4, 51.5, 8546, '190922', 931201, 464520, 60, 7742, 'weekly', 930319, 'B'),
 (6228, 77963, 4, 51.5, 8546, '290125', 931201, 464520, 60, 7742, 'weekly', 930319, 'B'),
 (6228, 77963, 4, 51.5, 8546, '385221', 931201, 464520, 60, 7742, 'weekly', 930319, 'B'),
 (6228, 77963, 4, 51.5, 8546, '351016', 931201, 464520, 60, 7742, 'weekly', 930319, 'B'),
 (6228, 77963, 4, 51.5, 8546, '430501', 931201, 464520, 60, 7742, 'weekly', 930319, 'B')]

11. Domiciliaciones en cuentas de actualización semanal de alquiler en cuentas de Praga

In [ ]:
%%sql
SELECT order_id, p.account_id, amount
FROM PERMANENT_ORDER p, ACCOUNT a, DISTRICT d
WHERE p.account_id = a.account_id
and a.district_id = d.A1
and k_symbol = "LEASING" 
and frequency = "weekly" -- Frecuencia sea semanal 
and A3 = "Prague"

 * sqlite:///data_berka.db
Done.

[(29514, 72, 2923),
 (30250, 573, 2249),
 (30944, 1056, 2531.7),
 (34056, 3141, 1087),
 (35237, 3959, 1680.6),
 (40429, 7465, 1060.6)]


12. Domiciliaciones (*órdenes*) semanales para alquiler (*leasing*) en cuentas de Praga

 - Ordenes permanentes de alquiler (*leasing*) y semanales (*weekly*)
 - Relación con cuentas que tienen región Praga

In [ ]:
%%sql
SELECT order_id, k_symbol, bank_to, a.account_id, a.frequency, d.A2, d.A3
FROM PERMANENT_ORDER p, ACCOUNT a, DISTRICT d
WHERE p.account_id = a.account_id and a.district_id = d.A1
    and k_symbol = "LEASING" and a.frequency = "weekly" and d.A3 = "Prague"

 * sqlite:///data_berka.db
Done.

[(29514, 'LEASING', 'OP', 72, 'weekly', 'Hl.m. Praha', 'Prague'),
 (30250, 'LEASING', 'CD', 573, 'weekly', 'Hl.m. Praha', 'Prague'),
 (30944, 'LEASING', 'IJ', 1056, 'weekly', 'Hl.m. Praha', 'Prague'),
 (34056, 'LEASING', 'OP', 3141, 'weekly', 'Hl.m. Praha', 'Prague'),
 (35237, 'LEASING', 'AB', 3959, 'weekly', 'Hl.m. Praha', 'Prague'),
 (40429, 'LEASING', 'ST', 7465, 'weekly', 'Hl.m. Praha', 'Prague')]

13. Transacciones relacionadas con pensiones (DUCHOD) en Plzen desde el banco MN

(limitar a 10)

In [ ]:
%%sql
SELECT trans_id, a.account_id, k_symbol, bank
FROM TRANS t, ACCOUNT a, DISTRICT d
WHERE t.account_id = a.account_id and a.district_id = d.A1
  and k_symbol = "DUCHOD" and bank = "MN" and d.A2 like "Plzen%" -- Like permite seleccionar las filas que coincidan con caracteres, fechas o patrones de números.
LIMIT 10

 * sqlite:///data_berka.db
Done.

[(47969, 161, 'DUCHOD', 'MN'),
 (47970, 161, 'DUCHOD', 'MN'),
 (47971, 161, 'DUCHOD', 'MN'),
 (47972, 161, 'DUCHOD', 'MN'),
 (47973, 161, 'DUCHOD', 'MN'),
 (47974, 161, 'DUCHOD', 'MN'),
 (47975, 161, 'DUCHOD', 'MN'),
 (47976, 161, 'DUCHOD', 'MN'),
 (47977, 161, 'DUCHOD', 'MN'),
 (1098524, 3753, 'DUCHOD', 'MN')]

# Subconsultas

14. Prestamos cuya cantidad es superior a la media de los clientes de Praga

- Cantidad media prestada a los cuentas de Praga

In [ ]:
%%sql
SELECT avg(l.amount)
FROM LOAN l, ACCOUNT a, DISTRICT D
WHERE l.account_id = a.account_id 
AND a.district_id = d.A1
AND d.A3 = "Prague"

 * sqlite:///data_berka.db
Done.

[(153957.2857142857,)]

- Consultar los préstamos superiores a esa cantidad

In [ ]:
%%sql
SELECT * FROM LOAN 
WHERE amount > (SELECT avg(l.amount)
        FROM LOAN l, ACCOUNT a, DISTRICT d
        WHERE l.account_id = a.account_id and a.district_id = d.A1  
        and d.A3 = "Prague")
ORDER BY amount DESC

Ahora en lugar de que se muestren los préstamos correspondientes a dicha consulta, se muestran la cantidad que hay de estos.

In [ ]:
%%sql
SELECT count(*)
FROM LOAN
WHERE amount > (SELECT avg(l.amount)
      FROM LOAN l, ACCOUNT a, DISTRICT D
      WHERE l.account_id = a.account_id 
      AND a.district_id = d.A1
      AND d.A3 = "Prague")

 * sqlite:///data_berka.db
Done.

[(277,)]

# Repaso de Join/Group By

## Objetivo 2.1

15 . Clientes de Praga con préstamos según su estado

- ¿Cuántos clientes hay en Praga?
- ¿Cuántas cuentas tienen asociados clientes en Praga?
- ¿cuántas de esas cuentas tienen asociados un préstamo?
- Necesito saber cuántos hay por cada estado (*status*)

In [ ]:
%%sql 
SELECT status, count(*)
FROM CLIENT c, DISTRICT d, DISPOSITION dp, LOAN l 
WHERE c.district_id = d.A1 and c.client_id = dp.client_id
and l.account_id = dp.account_id and d.A3 = "Prague"
GROUP BY status

 * sqlite:///data_berka.db
Done.

[('A', 37), ('B', 3), ('C', 55), ('D', 3)]

## Ejercicio

> cantidad de dinero medio en transacciones de clientes propietarios de cuentas en Kolin (owned accounts)

In [ ]:
%%sql
SELECT c.client_id, avg (amount) as av
from client c, district d, disposition ds, account a, trans t
WHERE c.district_id = d.A1 and c.client_id = ds.client_id
    and ds.account_id = a.account_id and a.account_id = t.account_id
and d.A2 = "Kolin" and ds.type = "OWNER" 
GROUP BY c.client_id
ORDER BY av DESC
LIMIT 10

 * sqlite:///data_berka.db
Done.

[(5249, 15611.831578947369),
 (3378, 14803.997402597402),
 (1388, 14464.587096774194),
 (6803, 13825.125153374232),
 (8091, 13227.722338204592),
 (3298, 13074.464857881138),
 (1806, 13037.759375),
 (4331, 12644.448051948051),
 (4974, 12023.291743119267),
 (3080, 11784.50460251046)]

> sanction interest if negative balance Cesky Krumlov


> stands for loan payment in Praha from the bank EF

# Extra: Left Join

1. ¿Cuántas cuentas hay? 4500
2. ¿Cuántas cuentas hay con préstamos? (inner join) 682
3. Cuentas con los datos de los préstamos si los hay
4. los ordenamos por cantidad

In [ ]:
%%sql 
SELECT a.account_id, a.date, l.amount, l.status, l.payments, l.duration
FROM ACCOUNT a INNER OUTER JOIN LOAN l ON a.account_id = l.account_id -- ON nos permite especificar una mayor variedad de condiciones de unión.
ORDER BY amount DESC

 * sqlite:///data_berka.db
(sqlite3.OperationalError) unknown or unsupported join type: INNER OUTER
[SQL: SELECT a.account_id, a.date, l.amount, l.status, l.payments, l.duration
FROM ACCOUNT a INNER OUTER JOIN LOAN l ON a.account_id = l.account_id -- ON nos permite especificar una mayor variedad de condiciones de unión.
ORDER BY amount DESC]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

LEFT OUTER JOIN, o simplemente Left Join, mantendrá los datos no relacionados de la izquierda (la primera) tabla.

# DataSets

---

Dataset sobre las transacciones con Vyskov, extrayendo los años de las diferentes fechas.

In [ ]:
%%sql dataset << SELECT substr(a.date,0,3) acc_year, substr(t.date, 0, 3) year,amount, balance, k_symbol
FROM ACCOUNT a, TRANS t, DISTRICT d
WHERE a.district_id = d.A1 and d.A2 = "Vyskov"
AND a.account_id = t.account_id

 * sqlite:///data_berka.db
Done.
Returning data to local variable dataset

In [ ]:
dataset.DataFrame().to_csv("dataset.csv")